version: '4.0'

services:
  # Rust/Axumアプリケーションのサービス
  app:
    # カレントディレクトリにあるDockerfileを使ってイメージをビルド
    build: .
    container_name: my-rust-app
    # ホストのポート8080をコンテナのポート8080にマッピング
    ports:
      - "8080:3000"
